name: deploy-live
on:
  push:
    branches:
      - live
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: mvn clean test
  build-and-deploy:
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: build_and_deploy
        run: |
          mvn clean package -DskipTests
          fileName=$(basename $(ls ./target/*.jar))
          cp ./target/$fileName /opt/webapps/family-moments/live/$fileName
          ln -sf /opt/webapps/family-moments/live/$fileName /opt/webapps/family-moments/live/family-moments.jar
          touch /opt/webapps/family-moments/live/restart